apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-gitlab
  namespace: gitlab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-gitlab
  template:
    metadata:
      labels:
        app: playground-gitlab
    spec:
      containers:
      - name: playground-gitlab
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground-gitlab
  namespace: gitlab-app
spec:
  type: LoadBalancer
  selector:
    app: playground-gitlab
  ports:
  - port: 8889
    targetPort: 8888