Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "mbrandaoS" do |s|
    s.vm.hostname = "mbrandaoS"
    s.vm.network "private_network", ip: "192.168.56.110"

    s.vm.synced_folder "./apps", "/home/vagrant/apps"

    s.vm.provision "shell", inline: <<-SHELL
      echo 'export PATH=$PATH:/usr/local/bin:/sbin' >> /home/vagrant/.profile
      echo 'alias k="kubectl"' >> /home/vagrant/.profile

      sudo apk update
      sudo apk add eudev util-linux e2fsprogs e2fsprogs-extra xz iptables ip6tables curl

      # Install K3s server
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip 192.168.56.110" \
        K3S_KUBECONFIG_MODE="644" sh -s -

        echo "Waiting for K3s to be ready..."
        while [ ! -f /etc/rancher/k3s/k3s.yaml ]; do
        sleep 2
        done
        echo "K3s is ready!"

        # Config for alpine
      mkdir -p /home/vagrant/.kube
      cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      chown -R vagrant:vagrant /home/vagrant/.kube

      echo "Waiting for K3s API to be ready..."
        until kubectl get nodes; do
        sleep 5
        done
        echo "K3s API is ready!"
      # Deploy
      kubectl apply -f /home/vagrant/apps

        sudo sh -c 'echo "192.168.56.110 app1.com" >> /etc/hosts'
        sudo sh -c 'echo "192.168.56.110 app2.com" >> /etc/hosts'
        sudo sh -c 'echo "192.168.56.110 app3.com" >> /etc/hosts'
    SHELL
  end
end
